# Generated by Django 4.2.3 on 2023-10-22 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('title', models.CharField(default='main', max_length=100)),
                ('code_description', models.CharField(default='A java code.', max_length=500)),
            ],
        ),
    ]
