# Generated by Django 4.2.3 on 2023-10-23 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='code',
            name='code_description',
        ),
        migrations.AlterField(
            model_name='code',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
