# Generated by Django 4.2.3 on 2023-10-23 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_remove_code_code_description_alter_code_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
